---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV.fetch('TK_CHEF_VERSION', 'true') %>

platforms:
- name: debian-jessie
- name: debian-wheezy
- name: debian-squeeze

suites:
- name: default
  run_list:
<% ENV.fetch('TK_RECIPES', 'default').split(/[ ,]+/).each do |recipe| %>
  - recipe[debian::<%= recipe %>]
<% end %>
- name: backports
  run_list:
  - recipe[debian::_backports_test]
