---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: debian-wheezy
- name: debian-squeeze

suites:
- name: default
  run_list:
<% ENV.fetch('RECIPES', 'default').split(/[ ,]+/).each do |recipe| %>
  - recipe[debian::<%= recipe %>]
<% end %>
- name: backports
  run_list:
  - recipe[debian::_backports_test]
