---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.0
  driver_config:
    box: debian-7.0
    box_url: https://reaktor-vm.s3.amazonaws.com/vagrant/debian-7.0.0_chef-11.4.4.box
- name: debian-6.0
  driver_config:
    box: debian-6.0
    box_url: https://reaktor-vm.s3.amazonaws.com/vagrant/debian-6.0.7_chef-11.4.4.box

suites:
- name: default
  run_list:
<% if !(recipes = ENV['RECIPES']) || recipes.empty? %>
  - recipe[minitest-handler]
  - recipe[debian_test]
<% else
     recipes.split(/[ ,]+/).each do |recipe| %>
  - recipe[debian::<%= recipe %>]
<%   end
   end %>
